# Generated by Django 4.0.4 on 2022-05-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
        ('students', '0002_remove_student_age'),
    ]

    operations = [
    ]
